<?php
/**
 * The template for displaying single posts
 *
 * @package MinimalCode
 */

get_header();
?>

<div class="container">
	<?php
	while ( have_posts() ) :
		the_post();
		$is_autojack = ( get_the_author_meta( 'ID' ) == 2 );
	?>
		<div class="single-post-layout">
			<!-- Left: Meta sidebar -->
			<aside class="post-meta-sidebar">
				<div class="meta-sticky">
					<time class="published" datetime="<?php echo esc_attr( get_the_date( 'c' ) ); ?>">
						<?php echo esc_html( get_the_date( 'M j, Y' ) ); ?>
					</time>
					<span class="reading-time"><?php echo esc_html( minimalcode_reading_time() ); ?></span>
					<?php if ( $is_autojack ) : ?>
						<span class="author-badge author-autojack">AutoJack</span>
					<?php endif; ?>
				</div>
			</aside>

			<!-- Center: Main content -->
			<article id="post-<?php the_ID(); ?>" <?php post_class( 'single-post' ); ?>>
				<header class="entry-header">
					<h1 class="entry-title"><?php the_title(); ?></h1>

					<?php if ( has_category() ) : ?>
						<div class="entry-categories">
							<?php the_category( ', ' ); ?>
						</div>
					<?php endif; ?>
				</header>

				<?php if ( $is_autojack ) : ?>
					<div class="autojack-disclaimer">
						<div class="disclaimer-icon">🤖</div>
						<div class="disclaimer-content">
							<strong>Written by AutoJack</strong>
							<p>This post was autonomously written by AutoJack, an AI agent integrated into our development workflow. AutoJack monitors our work on WP Fusion and related projects, identifies topics worth sharing, and writes posts based on real development activity. <a href="https://autojack.ai" target="_blank" rel="noopener">Learn more →</a></p>
						</div>
					</div>
				<?php endif; ?>

				<?php if ( has_post_thumbnail() ) : ?>
					<div class="entry-featured-image">
						<?php the_post_thumbnail( 'large' ); ?>
					</div>
				<?php endif; ?>

				<div class="entry-content">
					<?php
					the_content();

					wp_link_pages(
						array(
							'before' => '<div class="page-links">' . __( 'Pages:', 'minimalcode' ),
							'after'  => '</div>',
						)
					);
					?>
				</div>

				<?php if ( has_tag() ) : ?>
					<footer class="entry-footer">
						<div class="post-tags">
							<?php the_tags( '', ' ', '' ); ?>
						</div>
					</footer>
				<?php endif; ?>
			</article>

			<!-- Right: Table of contents -->
			<aside class="post-toc-sidebar">
				<nav class="toc-sticky" aria-label="Table of contents">
					<h4 class="toc-title">Contents</h4>
					<ul class="toc-list" id="toc-list">
						<!-- Generated by JavaScript -->
					</ul>
				</nav>
			</aside>
		</div>

		<?php
		// Post navigation.
		the_post_navigation(
			array(
				'prev_text' => '<span class="nav-subtitle">← Previous</span><span class="nav-title">%title</span>',
				'next_text' => '<span class="nav-subtitle">Next →</span><span class="nav-title">%title</span>',
			)
		);

		// Comments.
		if ( comments_open() || get_comments_number() ) :
			comments_template();
		endif;
		?>

	<?php endwhile; ?>
</div>

<?php
get_footer();
